import React, { useMemo, useState } from 'react';
import { Users, Wallet, Award, AlertTriangle, Search, CalendarDays, BarChart3 } from 'lucide-react';
import type { RawDonationRecord, AwardRecord } from '../types/donation';

const normalize=(s:string)=>s.trim().toLowerCase().replace(/\s+/g,' ');
const yearOf=(d:RawDonationRecord)=>Number((d.date||d.period||'').slice(0,4))||0;

export const ManagementDashboard:React.FC<{donations:RawDonationRecord[];awards:AwardRecord[]}> = ({donations,awards})=>{
 const [q,setQ]=useState('');
 const currentYear=new Date().getFullYear();
 const years=useMemo(()=>Array.from(new Set([...donations.map(yearOf),...awards.map(a=>Number(a.year)||0)].filter(y=>y>0))).sort((a,b)=>b-a),[donations,awards]);
 const [selectedYear,setSelectedYear]=useState<number|string>(currentYear);
 const yearDonations=useMemo(()=>selectedYear==='all'?donations:donations.filter(d=>yearOf(d)===selectedYear),[donations,selectedYear]);
 const yearAwards=useMemo(()=>selectedYear==='all'?awards:awards.filter(a=>Number(a.year)===selectedYear),[awards,selectedYear]);
 const donors=useMemo(()=>{const m=new Map<string,RawDonationRecord[]>(); yearDonations.forEach(d=>{const k=`${normalize(d.donorName)}|${d.idNumber||d.address}`; m.set(k,[...(m.get(k)||[]),d])}); return [...m.entries()].map(([k,rows])=>({k,name:rows[0].donorName,rows,total:rows.reduce((s,x)=>s+x.amount,0)})).sort((a,b)=>a.name.localeCompare(b.name,'ko'));},[yearDonations]);
 const total=yearDonations.reduce((s,d)=>s+d.amount,0);
 const awardPeople=new Set(yearAwards.map(a=>normalize(a.recipientName))).size;
 const filtered=donors.filter(x=>normalize(x.name).includes(normalize(q))).slice(0,50);
 const compareYears=years.slice(0,5).map(y=>({year:y,amount:donations.filter(d=>yearOf(d)===y).reduce((s,d)=>s+d.amount,0),people:new Set(donations.filter(d=>yearOf(d)===y).map(d=>normalize(d.donorName))).size,awards:awards.filter(a=>Number(a.year)===y).length}));
 const title=selectedYear==='all'?'전체기간':`${selectedYear}년`;
 return <main className="max-w-7xl mx-auto p-4 sm:p-6 space-y-6">
  <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-900">회원·회비·수상 통합현황</h2><p className="text-sm text-slate-500 mt-1">연도를 선택하여 해당 연도의 회비·후원 및 수상실적을 통합 조회합니다.</p></div><div className="bg-white border border-slate-200 rounded-xl p-3 flex items-center gap-3 shadow-sm"><CalendarDays className="w-5 h-5 text-blue-700"/><label className="text-sm font-medium">조회연도</label><select value={selectedYear} onChange={e=>setSelectedYear(e.target.value==='all'?'all':Number(e.target.value))} className="border rounded-lg px-3 py-2 text-sm font-semibold"><option value="all">전체기간</option>{!years.includes(currentYear)&&<option value={currentYear}>{currentYear}년</option>}{years.map(y=><option key={y} value={y}>{y}년</option>)}</select></div></div>
  <div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Card icon={<Users/>} label={`${title} 납부 회원`} value={`${donors.length}명`} /><Card icon={<Wallet/>} label={`${title} 회비/후원 합계`} value={`${total.toLocaleString()}원`} /><Card icon={<Award/>} label={`${title} 수상 회원`} value={`${awardPeople}명`} /><Card icon={<CalendarDays/>} label={`${title} 수상실적`} value={`${yearAwards.length}건`} /></div>
  <section className="bg-white border border-slate-200 rounded-xl shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><BarChart3 className="w-5 h-5 text-blue-700"/><div><h3 className="font-bold text-slate-900">연도별 비교 현황</h3><p className="text-xs text-slate-500">최근 등록된 5개 연도를 자동으로 비교합니다.</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="text-left p-3">연도</th><th className="text-right p-3">회비/후원금</th><th className="text-center p-3">납부 회원</th><th className="text-center p-3">수상실적</th></tr></thead><tbody>{compareYears.map(r=><tr key={r.year} className="border-t hover:bg-slate-50"><td className="p-3 font-bold">{r.year}년</td><td className="p-3 text-right">{r.amount.toLocaleString()}원</td><td className="p-3 text-center">{r.people}명</td><td className="p-3 text-center">{r.awards}건</td></tr>)}</tbody></table></div></section>
  <section className="bg-white border border-slate-200 rounded-xl shadow-sm p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4"><div><h3 className="font-bold text-slate-900">{title} 회원 납부현황</h3><p className="text-xs text-slate-500">선택한 연도 기준으로 회원별 납부액과 수상실적을 함께 확인합니다.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="회원명 검색" className="pl-9 pr-3 py-2 border rounded-lg text-sm"/></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="text-left p-3">회원명</th><th className="text-right p-3">납부액</th><th className="text-center p-3">납부 건수</th><th className="text-center p-3">수상실적</th><th className="text-left p-3">최근 납부일</th></tr></thead><tbody>{filtered.map(x=>{const name=normalize(x.name);const ac=yearAwards.filter(a=>normalize(a.recipientName)===name).length;const recent=[...x.rows].sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];return <tr key={x.k} className="border-t"><td className="p-3 font-medium">{x.name}</td><td className="p-3 text-right">{x.total.toLocaleString()}원</td><td className="p-3 text-center">{x.rows.length}건</td><td className="p-3 text-center">{ac}건</td><td className="p-3 text-slate-600">{recent?.date||recent?.period||'-'}</td></tr>})}</tbody></table></div>{filtered.length===0&&<div className="py-8 text-center text-slate-500">선택한 연도에 조회할 회원 자료가 없습니다.</div>}</section>
  <section className="border border-amber-200 bg-amber-50 rounded-xl p-4 flex gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0"/><div className="text-sm text-amber-900"><b>데이터 관리 안내:</b> 수상실적은 현재 기존 자료와의 호환성을 위해 성명 기반으로 표시됩니다. 동명이인 문제를 완전히 제거하려면 향후 회원 고유 memberId를 수상 자료에 연결하는 것이 필요합니다.</div></section>
 </main>
}
const Card=({icon,label,value}:{icon:React.ReactNode;label:string;value:string})=><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><div className="text-blue-900 mb-3">{icon}</div><div className="text-xs text-slate-500">{label}</div><div className="text-xl font-bold mt-1">{value}</div></div>;
