import React,{useMemo,useState} from 'react';
import {UserPlus, Pencil, Trash2, Search, Users} from 'lucide-react';
import type {MemberRecord,MemberStatus,MemberType,RawDonationRecord,AwardRecord} from '../types/donation';
const statusLabel:Record<MemberStatus,string>={active:'정상회원',inactive:'휴면회원',withdrawn:'탈퇴회원',exempt:'회비면제'};
const typeLabel:Record<MemberType,string>={regular:'일반회원',executive:'임원',sponsor:'후원회원',honorary:'명예회원'};
const empty=():MemberRecord=>({id:crypto.randomUUID(),memberNo:'',name:'',status:'active',memberType:'regular',joinDate:new Date().toISOString().slice(0,10),feePolicy:'월 회비'});
export const MemberManager:React.FC<{members:MemberRecord[];donations:RawDonationRecord[];awards:AwardRecord[];onSave:(m:MemberRecord)=>Promise<void>;onDelete:(id:string)=>Promise<void>}>=({members,donations,awards,onSave,onDelete})=>{
 const [editing,setEditing]=useState<MemberRecord|null>(null),[q,setQ]=useState(''),[saving,setSaving]=useState(false);
 const nextNo=useMemo(()=>String(Math.max(0,...members.map(m=>Number(m.memberNo)||0))+1).padStart(5,'0'),[members]);
 const filtered=members.filter(m=>`${m.name} ${m.memberNo}`.toLowerCase().includes(q.toLowerCase()));
 const submit=async()=>{if(!editing?.name.trim())return alert('회원명을 입력하세요.');setSaving(true);try{await onSave({...editing,memberNo:editing.memberNo||nextNo,updatedAt:new Date().toISOString(),createdAt:editing.createdAt||new Date().toISOString()});setEditing(null)}catch(e){alert('저장에 실패했습니다. Firebase 권한을 확인하세요.')}finally{setSaving(false)}};
 return <main className="max-w-7xl mx-auto p-4 sm:p-6 space-y-6"><div className="flex flex-col md:flex-row justify-between gap-3"><div><h2 className="text-2xl font-bold">회원 마스터 관리</h2><p className="text-sm text-slate-500 mt-1">회원번호·상태·구분·가입일·회비 기준을 직접 관리합니다.</p></div><button onClick={()=>setEditing({...empty(),memberNo:nextNo})} className="inline-flex items-center justify-center gap-2 bg-blue-900 text-white px-4 py-2 rounded-lg"><UserPlus className="w-4 h-4"/>회원 등록</button></div>
 <div className="grid grid-cols-1 md:grid-cols-4 gap-3">{(['active','inactive','withdrawn','exempt'] as MemberStatus[]).map(s=><div key={s} className="bg-white border rounded-xl p-4"><div className="text-xs text-slate-500">{statusLabel[s]}</div><div className="text-xl font-bold">{members.filter(m=>m.status===s).length}명</div></div>)}</div>
 <section className="bg-white border rounded-xl p-5"><div className="flex justify-between gap-3 mb-4"><div className="font-bold flex items-center gap-2"><Users className="w-5 h-5"/>회원 목록 ({members.length}명)</div><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input className="pl-9 py-2 border rounded-lg text-sm" placeholder="성명/회원번호 검색" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">회원번호</th><th className="p-3 text-left">성명</th><th>구분</th><th>상태</th><th>가입일</th><th>회비기준</th><th>회비기록</th><th>수상</th><th></th></tr></thead><tbody>{filtered.map(m=>{const name=m.name.trim().toLowerCase();const pay=donations.filter(d=>d.donorName.trim().toLowerCase()===name);const aw=awards.filter(a=>(a.memberId&&a.memberId===m.id)||a.recipientName.trim().toLowerCase()===name);return <tr key={m.id} className="border-t"><td className="p-3">{m.memberNo}</td><td className="p-3 font-medium">{m.name}</td><td className="text-center">{typeLabel[m.memberType]}</td><td className="text-center">{statusLabel[m.status]}</td><td className="text-center">{m.joinDate||'-'}</td><td className="text-center">{m.feePolicy||'-'}</td><td className="text-center">{pay.length}건</td><td className="text-center">{aw.length}건</td><td className="p-2 whitespace-nowrap"><button onClick={()=>setEditing(m)} className="p-2"><Pencil className="w-4 h-4"/></button><button onClick={async()=>{if(confirm(`${m.name} 회원을 삭제하시겠습니까?`))await onDelete(m.id)}} className="p-2 text-red-600"><Trash2 className="w-4 h-4"/></button></td></tr>})}</tbody></table></div></section>
 {editing&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-xl w-full max-w-xl p-6 space-y-4"><h3 className="text-lg font-bold">{members.some(m=>m.id===editing.id)?'회원 수정':'회원 등록'}</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[['회원번호','memberNo'],['성명','name'],['가입일','joinDate'],['회비 기준','feePolicy']].map(([l,k])=><label key={k} className="text-sm">{l}<input value={(editing as any)[k]||''} onChange={e=>setEditing({...editing,[k]:e.target.value})} className="mt-1 w-full border rounded-lg p-2" type={k==='joinDate'?'date':'text'}/></label>)}<label className="text-sm">회원구분<select value={editing.memberType} onChange={e=>setEditing({...editing,memberType:e.target.value as MemberType})} className="mt-1 w-full border rounded-lg p-2">{Object.entries(typeLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm">회원상태<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as MemberStatus})} className="mt-1 w-full border rounded-lg p-2">{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="px-4 py-2 border rounded-lg">취소</button><button disabled={saving} onClick={submit} className="px-4 py-2 bg-blue-900 text-white rounded-lg">{saving?'저장 중...':'저장'}</button></div></div></div>}</main>
}
