import type { RawDonationRecord } from '../types/donation';

const n=(v?:string)=>String(v||'').trim().replace(/\s+/g,' ').toLowerCase();
const nid=(v?:string)=>n(v).replace(/[-\s]/g,'');
const miss=(v?:string)=>{const x=n(v);return !x||['-','—','미등록','없음','미기재','미입력'].includes(x);};
const month=(r:RawDonationRecord)=>(r.date||r.period||'').slice(0,7);
const person=(r:RawDonationRecord)=>nid(r.idNumber)?`id:${nid(r.idNumber)}`:`name:${n(r.donorName)}`;
export function getDonationFingerprint(r:RawDonationRecord){if(r.sourceKey)return `source:${n(r.sourceKey)}`;return [person(r),n(r.date),month(r),Math.round(r.amount||0),n(r.paymentMethod),n(r.content)].join('|');}
const payment=(r:RawDonationRecord)=>[person(r),n(r.date)||month(r),Math.round(r.amount||0),n(r.paymentMethod),n(r.content)].join('|');
function samePerson(a:RawDonationRecord,b:RawDonationRecord){const ai=nid(a.idNumber),bi=nid(b.idNumber);if(ai&&bi)return ai===bi;if(n(a.donorName)!==n(b.donorName))return false;const aa=miss(a.address)?'':n(a.address),ba=miss(b.address)?'':n(b.address);return !(aa&&ba&&aa!==ba);}
function sameAttrs(a:RawDonationRecord,b:RawDonationRecord){if(Math.round(a.amount||0)!==Math.round(b.amount||0))return false;const ap=n(a.paymentMethod),bp=n(b.paymentMethod);if(ap&&bp&&ap!==bp)return false;const ac=n(a.content),bc=n(b.content);if(ac&&bc&&ac!==bc)return false;return true;}
function safeMerge(a:RawDonationRecord,b:RawDonationRecord){if(!samePerson(a,b)||!sameAttrs(a,b))return false;if(a.date&&b.date)return a.date===b.date;if(a.date&&!b.date)return false;if(!a.date&&b.date){const am=month(a),bm=month(b);return !am||!bm||am===bm;}return month(a)===month(b);}
function enrich(a:RawDonationRecord,b:RawDonationRecord):RawDonationRecord{return {...a,donorName:b.donorName||a.donorName,idNumber:!miss(b.idNumber)?b.idNumber.trim():(!miss(a.idNumber)?a.idNumber:''),address:!miss(b.address)?b.address.trim():(!miss(a.address)?a.address:''),date:b.date||a.date||'',period:b.period||a.period,paymentMethod:b.paymentMethod||a.paymentMethod||'계좌이체',donationType:b.donationType||a.donationType,donationCode:b.donationCode||a.donationCode,content:b.content||a.content||'후원금',amount:Math.round(b.amount||a.amount||0)};}
export function getStableDonationId(r:RawDonationRecord){const input=r.sourceKey?`source:${n(r.sourceKey)}`:payment(r);let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return `donation_${(h>>>0).toString(16).padStart(8,'0')}`;}
export function mergeDonationRecords(existing:RawDonationRecord[],incoming:RawDonationRecord[]){const records:RawDonationRecord[]=[],seen=new Set<string>(),source=new Map<string,number>(),added:RawDonationRecord[]=[],updated:RawDonationRecord[]=[];let duplicates=0;for(const raw of existing){const r={...raw,id:raw.id||getStableDonationId(raw),sourceKey:raw.sourceKey,idNumber:miss(raw.idNumber)?'':raw.idNumber.trim(),address:miss(raw.address)?'':raw.address.trim(),amount:Math.round(raw.amount||0)};const k=getDonationFingerprint(r);if(seen.has(k))continue;seen.add(k);if(r.sourceKey)source.set(n(r.sourceKey),records.length);records.push(r);}for(const raw of incoming){const r={...raw,id:getStableDonationId(raw),idNumber:miss(raw.idNumber)?'':raw.idNumber.trim(),address:miss(raw.address)?'':raw.address.trim(),date:raw.date||'',amount:Math.round(raw.amount||0)} as RawDonationRecord;if(r.sourceKey){const i=source.get(n(r.sourceKey));if(i!==undefined){const m=enrich(records[i],r);records[i]=m;updated.push(m);duplicates++;continue;}}const k=getDonationFingerprint(r);if(seen.has(k)){duplicates++;continue;}const c=records.map((x,i)=>({x,i})).filter(({x})=>safeMerge(x,r));if(c.length===1){const m=enrich(records[c[0].i],r);records[c[0].i]=m;updated.push(m);duplicates++;continue;}if(r.sourceKey)source.set(n(r.sourceKey),records.length);records.push(r);seen.add(k);added.push(r);}return {records,added,updated,duplicates};}
